spring:
 cloud:
   gateway:
     routes:
       - id: urlshortening
         uri: lb://URLSHORTENING
         predicates:
           - Path=/url/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**

