spring.application.name=urlshortening

spring.datasource.url=jdbc:h2:mem:urlshort
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
# http://localhost:8080/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=h2

# load data.sql 
sql.init.mode=always
# defer loading data.sql till tables are created.
spring.jpa.defer-datasource-initialization=true